In [1]:
# claiming the dataset
import pandas as pd

cxr_dataset = pd.read_csv("features.csv")
cxr_dataset.head()

Unnamed: 0      mean0    variance0  skewness0  uniformity0      snr0  \
0           0  70.153934  1897.820090   0.155578          154  1.610366   
1           1  67.943420  1640.924326   0.179606          158  1.677271   
2           2  85.324244  1666.530997  -0.291033          153  2.090094   
3           3  84.536424  1134.304302  -0.575772          129  2.510031   
4           4  97.321200  1344.070831  -0.521123          164  2.654583   

        mean1    variance1  skewness1  uniformity1  ...  variance14  \
0   67.820031  1431.488738   0.101886          149  ...         0.0   
1   62.438356  1516.524282   0.382945          153  ...         0.0   
2   61.805752  1425.903805   0.326995          145  ...         0.0   
3   85.243692   957.789884  -0.289562          136  ...         0.0   
4  102.034224  1417.579232  -0.313052          155  ...         0.0   

   skewness14  uniformity14  snr14      mean15  variance15  skewness15  \
0         0.0             0    0.0    0.000000    0.000000    0.000000   
1         0.0             0    0.0  125.818182   59.954257    0.105233   
2         0.0             0    0.0    0.000000    0.000000    0.000000   
3         0.0             0    0.0  105.758879  247.749337   -0.316222   
4         0.0             0    0.0  121.310059  518.784337   -0.373516   

   uniformity15      snr15     label  
0             0   0.000000  COVID-19  
1            38  16.249253  COVID-19  
2             0   0.000000  COVID-19  
3            64   6.719092  COVID-19  
4            95   5.326027  COVID-19  

[5 rows x 82 columns]

In [2]:
# Getting the features needed

#get the feature columns
col_features = list(cxr_dataset.columns)
#get the label column
label = list(cxr_dataset.columns).pop()
#deleting label column from col
del col_features[0]
del col_features[len(col_features) - 1]

features = cxr_dataset.loc[:, col_features].values
labels = cxr_dataset.loc[:, label].values

display(pd.DataFrame(features))

0            1         2      3         4           5   \
0    70.153934  1897.820090  0.155578  154.0  1.610366   67.820031   
1    67.943420  1640.924326  0.179606  158.0  1.677271   62.438356   
2    85.324244  1666.530997 -0.291033  153.0  2.090094   61.805752   
3    84.536424  1134.304302 -0.575772  129.0  2.510031   85.243692   
4    97.321200  1344.070831 -0.521123  164.0  2.654583  102.034224   
..         ...          ...       ...    ...       ...         ...   
295  67.485362   590.801404  0.125502  101.0  2.776443   58.764064   
296  57.642643  1138.936360  0.439436  135.0  1.708025   55.429969   
297  52.461857   967.863802  0.288745  120.0  1.686307   58.074462   
298  85.349291   861.184734 -0.512971  114.0  2.908384   57.942963   
299  54.742072   804.571951  0.265591  110.0  1.929918   46.046397   

              6         7      8         9   ...          70          71  \
0    1431.488738  0.101886  149.0  1.792520  ...    0.000000    0.000000   
1    1516.524282  0.382945  153.0  1.603344  ...    0.000000    0.000000   
2    1425.903805  0.326995  145.0  1.636755  ...    0.000000    0.000000   
3     957.789884 -0.289562  136.0  2.754401  ...    0.000000    0.000000   
4    1417.579232 -0.313052  155.0  2.710018  ...    0.000000    0.000000   
..           ...       ...    ...       ...  ...         ...         ...   
295  1009.093014 -0.076914  125.0  1.849891  ...  108.375000   24.734375   
296  1205.076900  0.298250  133.0  1.596751  ...    0.000000    0.000000   
297   876.051465  0.146898  131.0  1.962097  ...  113.789474    8.060942   
298  1208.748901  0.157751  123.0  1.666605  ...    0.000000    0.000000   
299  1082.516952  0.390843  125.0  1.399517  ...   92.851852  101.459534   

           72    73         74          75           76        77     78  \
0    0.000000   0.0   0.000000    0.000000     0.000000  0.000000    0.0   
1    0.000000   0.0   0.000000  125.818182    59.954257  0.105233   38.0   
2    0.000000   0.0   0.000000    0.000000     0.000000  0.000000    0.0   
3    0.000000   0.0   0.000000  105.758879   247.749337 -0.316222   64.0   
4    0.000000   0.0   0.000000  121.310059   518.784337 -0.373516   95.0   
..        ...   ...        ...         ...          ...       ...    ...   
295  0.136133   7.0  21.791074   46.903541  1214.512063  0.503447  120.0   
296  0.000000   0.0   0.000000  109.913580   392.893766 -2.253583   36.0   
297 -0.710812   7.0  40.078291   96.602423   387.369465  0.734007  104.0   
298  0.000000   0.0   0.000000   79.568421   959.213740 -0.612756   85.0   
299  0.206195  17.0   9.218158   49.546763  1256.728389  0.340671  115.0   

            79  
0     0.000000  
1    16.249253  
2     0.000000  
3     6.719092  
4     5.326027  
..         ...  
295   1.345875  
296   5.545156  
297   4.908235  
298   2.569112  
299   1.397638  

[300 rows x 80 columns]

In [20]:
from scipy import stats
import numpy as np

features = cxr_dataset.loc[:, ["mean0", "variance0", "skewness0", "uniformity0", "snr0"]].values

z = np.abs(stats.zscore(features))
print(z)

[[0.24320927 1.87617169 0.43296476 0.87388798 0.75048428]
 [0.36934887 1.28217805 0.49785133 1.01714831 0.68875892]
 [0.62246139 1.34138572 0.77308371 0.8380729  0.3078951 ]
 ...
 [1.25278072 0.27407055 0.79257287 0.34382478 0.68042244]
 [0.62389066 0.52073358 1.37241285 0.55871527 0.4470462 ]
 [1.12266375 0.65163349 0.73004672 0.70197559 0.45567084]]


In [21]:
threshold = 3
print(np.where(z > 3))

(array([ 81, 101, 101, 102, 129, 129, 163, 163, 175, 175, 209, 209],
      dtype=int64), array([4, 0, 4, 1, 3, 4, 0, 3, 0, 3, 1, 3], dtype=int64))


In [12]:
threshold = 3
print(len(np.where(z > 3)[0]))