# Retrieving the Dataset

In [22]:
# claiming the dataset
import pandas as pd

cxr_dataset = pd.read_csv("features.csv")
cxr_dataset.head()

area   perimeter  eccentricity  major axis  minor axis    contrast  \
0   8363  598.534055      0.697577  164.863765  118.126564  296.982764   
1   9469  659.362482      0.793141  190.814257  116.213102  122.146985   
2  11396  669.345238      0.806961  203.127645  119.968148  226.278844   
3  12532  779.002092      0.550650  187.560325  156.563338  529.477236   
4   5902  529.663997      0.837810  189.916672  103.687221  197.688291   

   homogeneity    energy  correlation   entropy        mean     variance  \
0     0.828278  0.784168     0.944170  2.109482  123.556858   599.227516   
1     0.812680  0.757011     0.923784  2.385392   57.059534   894.897091   
2     0.774707  0.708150     0.942846  2.879118   87.926816  1395.984641   
3     0.762863  0.677470     0.942298  2.933532  143.056416   549.747615   
4     0.890493  0.847027     0.945379  1.526313  117.577601   428.891555   

   skewness  uniformity       snr     label  
0 -0.284395         114  5.047438  COVID-19  
1 -0.121557         122  1.907400  COVID-19  
2 -0.145711         161  2.353320  COVID-19  
3  0.039205         106  6.101346  COVID-19  
4 -0.396287          98  5.677418  COVID-19

# Splitting the dataset to train and test

In [23]:
# Getting the features needed

#get the feature columns
col_features = list(cxr_dataset.columns)
#get the label column
label = list(cxr_dataset.columns).pop()
#deleting label column from col
del col_features[len(col_features) - 1]

features = cxr_dataset.loc[:, col_features].values
labels = cxr_dataset.loc[:, label].values

display(pd.DataFrame(features))

0           1         2           3           4           5   \
0     8363.0  598.534055  0.697577  164.863765  118.126564  296.982764   
1     9469.0  659.362482  0.793141  190.814257  116.213102  122.146985   
2    11396.0  669.345238  0.806961  203.127645  119.968148  226.278844   
3    12532.0  779.002092  0.550650  187.560325  156.563338  529.477236   
4     5902.0  529.663997  0.837810  189.916672  103.687221  197.688291   
..       ...         ...       ...         ...         ...         ...   
295  14388.0  761.161472  0.627040  191.246217  148.978404  384.562915   
296  10458.0  710.232539  0.725283  198.499311  136.656937  138.038844   
297  10938.0  731.688383  0.571715  177.165621  145.355895  390.779950   
298  14671.0  832.315801  0.537399  200.188207  168.824383  159.016281   
299  11012.0  761.345238  0.604818  178.366260  142.044356  151.281156   

           6         7         8         9           10           11  \
0    0.828278  0.784168  0.944170  2.109482  123.556858   599.227516   
1    0.812680  0.757011  0.923784  2.385392   57.059534   894.897091   
2    0.774707  0.708150  0.942846  2.879118   87.926816  1395.984641   
3    0.762863  0.677470  0.942298  2.933532  143.056416   549.747615   
4    0.890493  0.847027  0.945379  1.526313  117.577601   428.891555   
..        ...       ...       ...       ...         ...          ...   
295  0.719998  0.631385  0.931202  3.434403  102.508618  1021.830409   
296  0.847926  0.730934  0.949088  2.218025   82.779021   107.456905   
297  0.773507  0.718126  0.929993  2.714636  113.064637   885.195950   
298  0.794901  0.624005  0.949332  2.885598   81.125349   101.646546   
299  0.810535  0.716362  0.938875  2.543442   75.369869   363.638624   

           12     13        14  
0   -0.284395  114.0  5.047438  
1   -0.121557  122.0  1.907400  
2   -0.145711  161.0  2.353320  
3    0.039205  106.0  6.101346  
4   -0.396287   98.0  5.677418  
..        ...    ...       ...  
295  0.193422  138.0  3.206793  
296  0.332197   49.0  7.985519  
297  0.025558  131.0  3.800206  
298  0.312934   53.0  8.046560  
299 -0.233288   83.0  3.952417  

[300 rows x 15 columns]

In [24]:
from sklearn.model_selection import train_test_split

# Separating test and train dataset
train_features, test_features, train_lbl, test_lbl = train_test_split( features, labels, test_size=0.2, random_state=0)

In [25]:
#Standardizing the Dataset
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fitting of training dataset only
scaler.fit(train_features)

# Apply transform to both the training set and the test set.
train_features = scaler.transform(train_features)
test_features = scaler.transform(test_features)

# Applying Principal Component Analysis

In [26]:
# Feeding it to Principal Component Analysis
from sklearn.decomposition import PCA

# 5 different variance
variances = ["100%", "99%", "95%", "90%", "85%"]
pca = [PCA(1), PCA(.99), PCA(.95), PCA(.90), PCA(.85)]
# results of each PCA variance
pca_fit = []

for p in pca:
    pca_content = {"fit": None, "transforms": {"train": None, "test": None}}
    pca_content["fit"] = p.fit(train_features)
    pca_content["transforms"]["train"] = p.transform(train_features)
    pca_content["transforms"]["test"] = p.transform(test_features)
    pca_fit.append(pca_content)

In [27]:
# checking the number of Principal Component
print("From 14 features")
for i in range(len(variances)):
    print(f"Principal Components with {variances[i]} variance:", pca_fit[i]["fit"].n_components_)

From 14 features
Principal Components with 100% variance: 1
Principal Components with 99% variance: 9
Principal Components with 95% variance: 6
Principal Components with 90% variance: 5
Principal Components with 85% variance: 4


# Applying Linear Discriminant Analysis

### Libraries Needed

In [15]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import StratifiedKFold
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score

import numpy as np

lda = LinearDiscriminantAnalysis()

### With Principal Component Analysis

In [19]:
# Evaluating of Model
for i in range(len(pca_fit)):
    # define model evaluation method
    cv = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)
    # evaluate model
    scores = cross_val_score(lda, pca_fit[i]["transforms"]["train"], np.ravel(train_lbl), scoring='accuracy', cv=cv)
    # summarize result
    print('Variance of %s:\nMean Accuracy: %.4f (%.4f)\n' % (variances[i], np.mean(scores), np.std(scores)))

Variance of 100%:
Mean Accuracy: 0.3583 (0.0651)

Variance of 99%:
Mean Accuracy: 0.5625 (0.0918)

Variance of 95%:
Mean Accuracy: 0.5708 (0.1087)

Variance of 90%:
Mean Accuracy: 0.5250 (0.1090)

Variance of 85%:
Mean Accuracy: 0.5125 (0.1370)



In [29]:
#Train the model
results = [] # where all the results will place

for i in range(len(pca_fit)):
    lda.fit(pca_fit[i]["transforms"]["train"], np.ravel(train_lbl))
    predictions = lda.predict(pca_fit[i]["transforms"]["test"])
    results.append(predictions)

In [40]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

for i in range(len(pca_fit)):
    print("Variance of", variances[i])
    print("Accuracy Score -", accuracy_score(test_lbl, results[i]))
    
    print("Confusion Matrix")
    print(confusion_matrix(test_lbl, results[i]))
    
    print("Classification Report")
    print(classification_report(test_lbl, results[i]))
    
    print()

Variance of 100%
Accuracy Score - 0.38333333333333336
Confusion Matrix
[[ 0 11  9]
 [ 2 11  7]
 [ 0  8 12]]
Classification Report
              precision    recall  f1-score   support

    COVID-19       0.00      0.00      0.00        20
  No Finding       0.37      0.55      0.44        20
   Pneumonia       0.43      0.60      0.50        20

    accuracy                           0.38        60
   macro avg       0.27      0.38      0.31        60
weighted avg       0.27      0.38      0.31        60


Variance of 99%
Accuracy Score - 0.5833333333333334
Confusion Matrix
[[10  6  4]
 [ 0 15  5]
 [ 5  5 10]]
Classification Report
              precision    recall  f1-score   support

    COVID-19       0.67      0.50      0.57        20
  No Finding       0.58      0.75      0.65        20
   Pneumonia       0.53      0.50      0.51        20

    accuracy                           0.58        60
   macro avg       0.59      0.58      0.58        60
weighted avg       0.59      0.58 

### Without Principal Component Analysis

In [42]:
# Performing towards the untransformed dataset

# define model evaluation method
cv = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)

# evaluate model
scores = cross_val_score(lda, train_features, np.ravel(train_lbl), scoring='accuracy', cv=cv)

# summarize result
print('Linear Discriminant Analysis Cross Validation Score:\nMean Accuracy - %.4f (%.4f)\n' % (np.mean(scores), np.std(scores)))

Linear Discriminant Analysis Cross Validation Score:
Mean Accuracy - 0.6042 (0.1137)



In [43]:
lda.fit(train_features, np.ravel(train_lbl))
predictions = lda.predict(test_features)

In [44]:
print("Linear Disriminant Analysis Performance")
print("Accuracy Score -", accuracy_score(test_lbl, predictions))

print("Confusion Matrix")
print(confusion_matrix(test_lbl, predictions))

print("Classification Report")
print(classification_report(test_lbl, predictions))

Linear Disriminant Analysis Performance
Accuracy Score - 0.6166666666666667
Confusion Matrix
[[13  2  5]
 [ 1 16  3]
 [ 7  5  8]]
Classification Report
              precision    recall  f1-score   support

    COVID-19       0.62      0.65      0.63        20
  No Finding       0.70      0.80      0.74        20
   Pneumonia       0.50      0.40      0.44        20

    accuracy                           0.62        60
   macro avg       0.60      0.62      0.61        60
weighted avg       0.60      0.62      0.61        60

