# Retrieving the Dataset

In [1]:
# claiming the dataset
import pandas as pd

cxr_dataset = pd.read_csv("features.csv")
cxr_dataset.head()

Unnamed: 0  area   perimeter  eccentricity  major axis  minor axis  \
0           0  6518  526.592929      0.887730  198.105599   91.200867   
1           1  9375  647.806133      0.828264  205.513966  115.157352   
2           2  9413  634.877200      0.856131  210.678586  108.870141   
3           3  9801  707.546248      0.800774  216.524568  129.690916   
4           4  9314  957.504617      0.904771  260.378375  110.894820   

     contrast  homogeneity    energy  correlation   entropy       mean  \
0  157.943366     0.854284  0.841933     0.801273  1.533093  49.499035   
1  168.538035     0.792434  0.767159     0.826483  2.141924  45.942830   
2  165.910877     0.801393  0.770478     0.850527  2.152794  49.395408   
3  180.991978     0.781750  0.751488     0.826203  2.251974  46.978399   
4  217.065132     0.798402  0.772575     0.842419  2.166329  56.588928   

     variance  skewness  uniformity       snr     label  
0  658.165072  0.008017         120  1.929431  COVID-19  
1  615.794529  0.033062         112  1.851398  COVID-19  
2  654.809157 -0.010580         102  1.930320  COVID-19  
3  555.900959 -0.062853         111  1.992505  COVID-19  
4  738.553988 -0.046816         141  2.082286  COVID-19

# Splitting the dataset to train and test

In [2]:
# Getting the features needed

#get the feature columns
col_features = list(cxr_dataset.columns)
#get the label column
label = list(cxr_dataset.columns).pop()
#deleting label column from col
del col_features[0]
del col_features[len(col_features) - 1]

features = cxr_dataset.loc[:, col_features].values
labels = cxr_dataset.loc[:, label].values

display(pd.DataFrame(features))

0            1         2           3           4           5   \
0     6518.0   526.592929  0.887730  198.105599   91.200867  157.943366   
1     9375.0   647.806133  0.828264  205.513966  115.157352  168.538035   
2     9413.0   634.877200  0.856131  210.678586  108.870141  165.910877   
3     9801.0   707.546248  0.800774  216.524568  129.690916  180.991978   
4     9314.0   957.504617  0.904771  260.378375  110.894820  217.065132   
..       ...          ...       ...         ...         ...         ...   
295  15556.0  1015.653896  0.640768  242.049702  185.829988  223.637786   
296  14041.0   772.759451  0.793892  226.060095  137.457868  214.151923   
297  17248.0   945.085353  0.611615  227.983427  180.370303  194.608256   
298  17236.0   918.842712  0.689811  240.821141  174.352064  218.873845   
299  15588.0   934.984848  0.684240  238.034787  173.588474  230.793985   

           6         7         8         9          10          11        12  \
0    0.854284  0.841933  0.801273  1.533093  49.499035  658.165072  0.008017   
1    0.792434  0.767159  0.826483  2.141924  45.942830  615.794529  0.033062   
2    0.801393  0.770478  0.850527  2.152794  49.395408  654.809157 -0.010580   
3    0.781750  0.751488  0.826203  2.251974  46.978399  555.900959 -0.062853   
4    0.798402  0.772575  0.842419  2.166329  56.588928  738.553988 -0.046816   
..        ...       ...       ...       ...        ...         ...       ...   
295  0.660449  0.605939  0.826710  3.308360  44.163774  511.329247 -0.079256   
296  0.695627  0.645357  0.832257  3.066808  44.345364  605.196593  0.106919   
297  0.631773  0.559814  0.811121  3.547618  37.803748  403.298135  0.284334   
298  0.623339  0.560574  0.776001  3.552407  35.716039  435.134642  0.484559   
299  0.659237  0.607013  0.819709  3.329255  44.178172  491.725182  0.225518   

        13        14  
0    120.0  1.929431  
1    112.0  1.851398  
2    102.0  1.930320  
3    111.0  1.992505  
4    141.0  2.082286  
..     ...       ...  
295  100.0  1.953061  
296  110.0  1.802603  
297  101.0  1.882443  
298  114.0  1.712188  
299  113.0  1.992262  

[300 rows x 15 columns]

In [3]:
from sklearn.model_selection import train_test_split

# Separating test and train dataset
train_features, test_features, train_lbl, test_lbl = train_test_split( features, labels, test_size=0.2, random_state=0)

In [4]:
#Standardizing the Dataset
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fitting of training dataset only
scaler.fit(train_features)

# Apply transform to both the training set and the test set.
train_features = scaler.transform(train_features)
test_features = scaler.transform(test_features)

# Applying Principal Component Analysis

In [5]:
# Feeding it to Principal Component Analysis
from sklearn.decomposition import PCA

# 5 different variance
variances = ["100%", "99%", "95%", "90%", "85%"]
pca = [PCA(), PCA(.99), PCA(.95), PCA(.90), PCA(.85)]
# results of each PCA variance
pca_fit = []

for p in pca:
    pca_content = {"fit": None, "transforms": {"train": None, "test": None}}
    pca_content["fit"] = p.fit(train_features)
    pca_content["transforms"]["train"] = p.transform(train_features)
    pca_content["transforms"]["test"] = p.transform(test_features)
    pca_fit.append(pca_content)

In [6]:
# checking the number of Principal Component
print("From 14 features")
for i in range(len(variances)):
    print(f"Principal Components with {variances[i]} variance:", pca_fit[i]["fit"].n_components_)

From 14 features
Principal Components with 100% variance: 15
Principal Components with 99% variance: 8
Principal Components with 95% variance: 6
Principal Components with 90% variance: 5
Principal Components with 85% variance: 4


# Applying Linear Discriminant Analysis

### Libraries Needed

In [7]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import StratifiedKFold
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score

import numpy as np

lda = LinearDiscriminantAnalysis()

### With Principal Component Analysis

In [8]:
# Evaluating of Model
for i in range(len(pca_fit)):
    # define model evaluation method
    cv = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)
    # evaluate model
    scores = cross_val_score(lda, pca_fit[i]["transforms"]["train"], np.ravel(train_lbl), scoring='accuracy', cv=cv)
    # summarize result
    print('Variance of %s:\nMean Accuracy: %.4f (%.4f)\n' % (variances[i], np.mean(scores), np.std(scores)))

Variance of 100%:
Mean Accuracy: 0.6042 (0.1167)

Variance of 99%:
Mean Accuracy: 0.5542 (0.0914)

Variance of 95%:
Mean Accuracy: 0.5625 (0.0796)

Variance of 90%:
Mean Accuracy: 0.5333 (0.0667)

Variance of 85%:
Mean Accuracy: 0.5542 (0.0895)



In [9]:
#Train the model
results = [] # where all the results will place

for i in range(len(pca_fit)):
    lda.fit(pca_fit[i]["transforms"]["train"], np.ravel(train_lbl))
    predictions = lda.predict(pca_fit[i]["transforms"]["test"])
    results.append(predictions)

In [10]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

for i in range(len(pca_fit)):
    print("Variance of", variances[i])
    print("Accuracy Score -", accuracy_score(test_lbl, results[i]))
    
    print("Confusion Matrix")
    print(confusion_matrix(test_lbl, results[i]))
    
    print("Classification Report")
    print(classification_report(test_lbl, results[i]))
    
    print()

Variance of 100%
Accuracy Score - 0.6166666666666667
Confusion Matrix
[[12  3  5]
 [ 0 18  2]
 [10  3  7]]
Classification Report
              precision    recall  f1-score   support

    COVID-19       0.55      0.60      0.57        20
  No Finding       0.75      0.90      0.82        20
   Pneumonia       0.50      0.35      0.41        20

    accuracy                           0.62        60
   macro avg       0.60      0.62      0.60        60
weighted avg       0.60      0.62      0.60        60


Variance of 99%
Accuracy Score - 0.48333333333333334
Confusion Matrix
[[ 8  5  7]
 [ 1 16  3]
 [12  3  5]]
Classification Report
              precision    recall  f1-score   support

    COVID-19       0.38      0.40      0.39        20
  No Finding       0.67      0.80      0.73        20
   Pneumonia       0.33      0.25      0.29        20

    accuracy                           0.48        60
   macro avg       0.46      0.48      0.47        60
weighted avg       0.46      0.48 

### Without Principal Component Analysis

In [11]:
# Performing towards the untransformed dataset

# define model evaluation method
cv = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)

# evaluate model
scores = cross_val_score(lda, train_features, np.ravel(train_lbl), scoring='accuracy', cv=cv)

# summarize result
print('Linear Discriminant Analysis Cross Validation Score:\nMean Accuracy - %.4f (%.4f)\n' % (np.mean(scores), np.std(scores)))

Linear Discriminant Analysis Cross Validation Score:
Mean Accuracy - 0.6042 (0.1167)



In [12]:
lda.fit(train_features, np.ravel(train_lbl))
predictions = lda.predict(test_features)

In [13]:
print("Linear Disriminant Analysis Performance")
print("Accuracy Score -", accuracy_score(test_lbl, predictions))

print("Confusion Matrix")
print(confusion_matrix(test_lbl, predictions))

print("Classification Report")
print(classification_report(test_lbl, predictions))

Linear Disriminant Analysis Performance
Accuracy Score - 0.6166666666666667
Confusion Matrix
[[12  3  5]
 [ 0 18  2]
 [10  3  7]]
Classification Report
              precision    recall  f1-score   support

    COVID-19       0.55      0.60      0.57        20
  No Finding       0.75      0.90      0.82        20
   Pneumonia       0.50      0.35      0.41        20

    accuracy                           0.62        60
   macro avg       0.60      0.62      0.60        60
weighted avg       0.60      0.62      0.60        60

