# Retrieving the Dataset

In [1]:
# claiming the dataset
import pandas as pd

cxr_dataset = pd.read_csv("../features.csv")
cxr_dataset.head()

Unnamed: 0  area   perimeter  eccentricity  major axis  minor axis  \
0           0  6518  526.592929      0.887730  198.105599   91.200867   
1           1  9375  647.806133      0.828264  205.513966  115.157352   
2           2  9413  634.877200      0.856131  210.678586  108.870141   
3           3  9801  707.546248      0.800774  216.524568  129.690916   
4           4  9314  957.504617      0.904771  260.378375  110.894820   

     contrast  homogeneity    energy  correlation   entropy       mean  \
0  157.943366     0.854284  0.841933     0.801273  1.533093  49.499035   
1  168.538035     0.792434  0.767159     0.826483  2.141924  45.942830   
2  165.910877     0.801393  0.770478     0.850527  2.152794  49.395408   
3  180.991978     0.781750  0.751488     0.826203  2.251974  46.978399   
4  217.065132     0.798402  0.772575     0.842419  2.166329  56.588928   

     variance  skewness  uniformity       snr     label  
0  658.165072  0.008017         120  1.929431  COVID-19  
1  615.794529  0.033062         112  1.851398  COVID-19  
2  654.809157 -0.010580         102  1.930320  COVID-19  
3  555.900959 -0.062853         111  1.992505  COVID-19  
4  738.553988 -0.046816         141  2.082286  COVID-19

In [2]:
drop_rows = cxr_dataset.loc[cxr_dataset['label'] == 'COVID-19']
cxr_dataset.drop(drop_rows.index, inplace=True)
cxr_dataset['label'].unique()

array(['Pneumonia', 'No Finding'], dtype=object)

# Splitting the dataset to train and test

In [3]:
# Getting the features needed

#get the feature columns
col_features = list(cxr_dataset.columns)
#get the label column
label = list(cxr_dataset.columns).pop()
#deleting label column from col
del col_features[0]
del col_features[len(col_features) - 1]

features = cxr_dataset.loc[:, col_features].values
labels = cxr_dataset.loc[:, label].values

display(pd.DataFrame(features))

0            1         2           3           4           5   \
0    12226.0   839.629509  0.752546  224.116275  147.589515  243.599135   
1     7384.0   689.587878  0.866594  247.356704  123.434291  211.817949   
2    10688.0   603.681241  0.944236  269.329384   88.681966  113.256604   
3    10803.0   999.913780  0.657119  230.074719  173.427358  278.789964   
4    13338.0  1141.612265  0.718199  242.561158  168.783335  252.745228   
..       ...          ...       ...         ...         ...         ...   
195  15556.0  1015.653896  0.640768  242.049702  185.829988  223.637786   
196  14041.0   772.759451  0.793892  226.060095  137.457868  214.151923   
197  17248.0   945.085353  0.611615  227.983427  180.370303  194.608256   
198  17236.0   918.842712  0.689811  240.821141  174.352064  218.873845   
199  15588.0   934.984848  0.684240  238.034787  173.588474  230.793985   

           6         7         8         9          10           11        12  \
0    0.726162  0.689334  0.813831  2.731821  47.559561   652.611716 -0.067080   
1    0.832496  0.816281  0.795727  1.732296  53.905637   685.107795 -0.192135   
2    0.771412  0.743201  0.945485  2.562788  60.161405  1679.564244  0.978585   
3    0.743684  0.720387  0.783213  2.469851  50.504678   623.607263  0.004220   
4    0.700992  0.661393  0.784854  2.934372  43.179180   582.501596  0.238537   
..        ...       ...       ...       ...        ...          ...       ...   
195  0.660449  0.605939  0.826710  3.308360  44.163774   511.329247 -0.079256   
196  0.695627  0.645357  0.832257  3.066808  44.345364   605.196593  0.106919   
197  0.631773  0.559814  0.811121  3.547618  37.803748   403.298135  0.284334   
198  0.623339  0.560574  0.776001  3.552407  35.716039   435.134642  0.484559   
199  0.659237  0.607013  0.819709  3.329255  44.178172   491.725182  0.225518   

        13        14  
0    113.0  1.861703  
1    119.0  2.059466  
2    189.0  1.467978  
3    126.0  2.022442  
4    120.0  1.789064  
..     ...       ...  
195  100.0  1.953061  
196  110.0  1.802603  
197  101.0  1.882443  
198  114.0  1.712188  
199  113.0  1.992262  

[200 rows x 15 columns]

In [4]:
from sklearn.model_selection import train_test_split

# Separating test and train dataset
train_features, test_features, train_lbl, test_lbl = train_test_split( features, labels, test_size=0.2, random_state=0)

In [5]:
#Standardizing the Dataset
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fitting of training dataset only
scaler.fit(train_features)

# Apply transform to both the training set and the test set.
train_features = scaler.transform(train_features)
test_features = scaler.transform(test_features)

# Applying Principal Component Analysis

In [6]:
# Feeding it to Principal Component Analysis
from sklearn.decomposition import PCA

# 5 different variance
variances = ["100%", "99%", "95%", "90%", "85%"]
pca = [PCA(), PCA(.99), PCA(.95), PCA(.90), PCA(.85)]
# results of each PCA variance
pca_fit = []

for p in pca:
    pca_content = {"fit": None, "transforms": {"train": None, "test": None}}
    pca_content["fit"] = p.fit(train_features)
    pca_content["transforms"]["train"] = p.transform(train_features)
    pca_content["transforms"]["test"] = p.transform(test_features)
    pca_fit.append(pca_content)

In [7]:
# checking the number of Principal Component
print("From 14 features")
for i in range(len(variances)):
    print(f"Principal Components with {variances[i]} variance:", pca_fit[i]["fit"].n_components_)

From 14 features
Principal Components with 100% variance: 15
Principal Components with 99% variance: 8
Principal Components with 95% variance: 6
Principal Components with 90% variance: 5
Principal Components with 85% variance: 4


# Applying Linear Discriminant Analysis

### Libraries Needed

In [8]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import StratifiedKFold
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score

import numpy as np

lda = LinearDiscriminantAnalysis()

### With Principal Component Analysis

In [9]:
# Evaluating of Model
for i in range(len(pca_fit)):
    # define model evaluation method
    cv = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)
    # evaluate model
    scores = cross_val_score(lda, pca_fit[i]["transforms"]["train"], np.ravel(train_lbl), scoring='accuracy', cv=cv)
    # summarize result
    print('Variance of %s:\nMean Accuracy: %.4f (%.4f)\n' % (variances[i], np.mean(scores), np.std(scores)))

Variance of 100%:
Mean Accuracy: 0.7438 (0.1201)

Variance of 99%:
Mean Accuracy: 0.7500 (0.0884)

Variance of 95%:
Mean Accuracy: 0.7812 (0.0850)

Variance of 90%:
Mean Accuracy: 0.7937 (0.0841)

Variance of 85%:
Mean Accuracy: 0.7688 (0.1010)



In [10]:
#Train the model
results = [] # where all the results will place

for i in range(len(pca_fit)):
    lda.fit(pca_fit[i]["transforms"]["train"], np.ravel(train_lbl))
    predictions = lda.predict(pca_fit[i]["transforms"]["test"])
    results.append(predictions)

In [11]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

for i in range(len(pca_fit)):
    print("Variance of", variances[i])
    print("Accuracy Score -", accuracy_score(test_lbl, results[i]))
    
    print("Confusion Matrix")
    print(confusion_matrix(test_lbl, results[i]))
    
    print("Classification Report")
    print(classification_report(test_lbl, results[i]))
    
    print()

Variance of 100%
Accuracy Score - 0.85
Confusion Matrix
[[20  2]
 [ 4 14]]
Classification Report
              precision    recall  f1-score   support

  No Finding       0.83      0.91      0.87        22
   Pneumonia       0.88      0.78      0.82        18

    accuracy                           0.85        40
   macro avg       0.85      0.84      0.85        40
weighted avg       0.85      0.85      0.85        40


Variance of 99%
Accuracy Score - 0.825
Confusion Matrix
[[19  3]
 [ 4 14]]
Classification Report
              precision    recall  f1-score   support

  No Finding       0.83      0.86      0.84        22
   Pneumonia       0.82      0.78      0.80        18

    accuracy                           0.82        40
   macro avg       0.82      0.82      0.82        40
weighted avg       0.82      0.82      0.82        40


Variance of 95%
Accuracy Score - 0.8
Confusion Matrix
[[19  3]
 [ 5 13]]
Classification Report
              precision    recall  f1-score   support



### Without Principal Component Analysis

In [12]:
# Performing towards the untransformed dataset

# define model evaluation method
cv = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)

# evaluate model
scores = cross_val_score(lda, train_features, np.ravel(train_lbl), scoring='accuracy', cv=cv)

# summarize result
print('Linear Discriminant Analysis Cross Validation Score:\nMean Accuracy - %.4f (%.4f)\n' % (np.mean(scores), np.std(scores)))

Linear Discriminant Analysis Cross Validation Score:
Mean Accuracy - 0.7438 (0.1201)



In [13]:
lda.fit(train_features, np.ravel(train_lbl))
predictions = lda.predict(test_features)

In [14]:
print("Linear Disriminant Analysis Performance")
print("Accuracy Score -", accuracy_score(test_lbl, predictions))

print("Confusion Matrix")
print(confusion_matrix(test_lbl, predictions))

print("Classification Report")
print(classification_report(test_lbl, predictions))

Linear Disriminant Analysis Performance
Accuracy Score - 0.85
Confusion Matrix
[[20  2]
 [ 4 14]]
Classification Report
              precision    recall  f1-score   support

  No Finding       0.83      0.91      0.87        22
   Pneumonia       0.88      0.78      0.82        18

    accuracy                           0.85        40
   macro avg       0.85      0.84      0.85        40
weighted avg       0.85      0.85      0.85        40

