# Retrieving the Dataset

In [1]:
# claiming the dataset
import pandas as pd

cxr_dataset = pd.read_csv("../features.csv")
cxr_dataset.head()

Unnamed: 0      mean0    variance0  skewness0  uniformity0      snr0  \
0           0  70.153934  1897.820090   0.155578          154  1.610366   
1           1  67.943420  1640.924326   0.179606          158  1.677271   
2           2  85.324244  1666.530997  -0.291033          153  2.090094   
3           3  84.536424  1134.304302  -0.575772          129  2.510031   
4           4  97.321200  1344.070831  -0.521123          164  2.654583   

        mean1    variance1  skewness1  uniformity1  ...  variance14  \
0   67.820031  1431.488738   0.101886          149  ...         0.0   
1   62.438356  1516.524282   0.382945          153  ...         0.0   
2   61.805752  1425.903805   0.326995          145  ...         0.0   
3   85.243692   957.789884  -0.289562          136  ...         0.0   
4  102.034224  1417.579232  -0.313052          155  ...         0.0   

   skewness14  uniformity14  snr14      mean15  variance15  skewness15  \
0         0.0             0    0.0    0.000000    0.000000    0.000000   
1         0.0             0    0.0  125.818182   59.954257    0.105233   
2         0.0             0    0.0    0.000000    0.000000    0.000000   
3         0.0             0    0.0  105.758879  247.749337   -0.316222   
4         0.0             0    0.0  121.310059  518.784337   -0.373516   

   uniformity15      snr15     label  
0             0   0.000000  COVID-19  
1            38  16.249253  COVID-19  
2             0   0.000000  COVID-19  
3            64   6.719092  COVID-19  
4            95   5.326027  COVID-19  

[5 rows x 82 columns]

In [2]:
drop_rows = cxr_dataset.loc[cxr_dataset['label'] == 'COVID-19']
cxr_dataset.drop(drop_rows.index, inplace=True)
cxr_dataset['label'].unique()

array(['Pneumonia', 'No Finding'], dtype=object)

# Splitting the dataset to train and test

In [3]:
# Getting the features needed

#get the feature columns
col_features = list(cxr_dataset.columns)
#get the label column
label = list(cxr_dataset.columns).pop()
#deleting label column from col
del col_features[0]
del col_features[len(col_features) - 1]

features = cxr_dataset.loc[:, col_features].values
labels = cxr_dataset.loc[:, label].values

display(pd.DataFrame(features))

0            1         2      3         4           5   \
0     64.886621  1354.371121  0.042737  138.0  1.763138   67.094969   
1    131.718023   375.481536 -1.061614   80.0  6.797527  120.269347   
2     77.013218  2487.350327  0.415121  182.0  1.544176   70.518231   
3     93.971731  1008.561038 -0.644343  130.0  2.959008   69.500000   
4     73.097087  1649.196885  0.185183  158.0  1.799964   70.979567   
..          ...          ...       ...    ...       ...         ...   
195   67.485362   590.801404  0.125502  101.0  2.776443   58.764064   
196   57.642643  1138.936360  0.439436  135.0  1.708025   55.429969   
197   52.461857   967.863802  0.288745  120.0  1.686307   58.074462   
198   85.349291   861.184734 -0.512971  114.0  2.908384   57.942963   
199   54.742072   804.571951  0.265591  110.0  1.929918   46.046397   

              6         7      8         9   ...          70           71  \
0    1382.059534  0.078240  143.0  1.804790  ...    0.000000     0.000000   
1     578.597406 -0.519057  110.0  4.999962  ...    0.000000     0.000000   
2    1621.148652  0.435528  154.0  1.751419  ...    0.000000     0.000000   
3    1755.016344  0.290876  167.0  1.658992  ...   84.653846  1308.534024   
4    1261.278429  0.050383  143.0  1.998609  ...    0.000000     0.000000   
..           ...       ...    ...       ...  ...         ...          ...   
195  1009.093014 -0.076914  125.0  1.849891  ...  108.375000    24.734375   
196  1205.076900  0.298250  133.0  1.596751  ...    0.000000     0.000000   
197   876.051465  0.146898  131.0  1.962097  ...  113.789474     8.060942   
198  1208.748901  0.157751  123.0  1.666605  ...    0.000000     0.000000   
199  1082.516952  0.390843  125.0  1.399517  ...   92.851852   101.459534   

           72    73         74          75           76        77     78  \
0    0.000000   0.0   0.000000   87.020202   917.252117 -0.172587   65.0   
1    0.000000   0.0   0.000000   90.463889  2065.109807  0.167476  136.0   
2    0.000000   0.0   0.000000    0.000000     0.000000  0.000000    0.0   
3   -0.485427  23.0   2.340207   86.173565  1531.564001 -0.490912  138.0   
4    0.000000   0.0   0.000000   98.984615   251.830533  0.473112   42.0   
..        ...   ...        ...         ...          ...       ...    ...   
195  0.136133   7.0  21.791074   46.903541  1214.512063  0.503447  120.0   
196  0.000000   0.0   0.000000  109.913580   392.893766 -2.253583   36.0   
197 -0.710812   7.0  40.078291   96.602423   387.369465  0.734007  104.0   
198  0.000000   0.0   0.000000   79.568421   959.213740 -0.612756   85.0   
199  0.206195  17.0   9.218158   49.546763  1256.728389  0.340671  115.0   

           79  
0    2.873265  
1    1.990690  
2    0.000000  
3    2.201945  
4    6.237542  
..        ...  
195  1.345875  
196  5.545156  
197  4.908235  
198  2.569112  
199  1.397638  

[200 rows x 80 columns]

In [4]:
from sklearn.model_selection import train_test_split

# Separating test and train dataset
train_features, test_features, train_lbl, test_lbl = train_test_split( features, labels, test_size=0.2, random_state=0)

In [5]:
#Standardizing the Dataset
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fitting of training dataset only
scaler.fit(train_features)

# Apply transform to both the training set and the test set.
train_features = scaler.transform(train_features)
test_features = scaler.transform(test_features)

# Applying Principal Component Analysis

In [6]:
# Feeding it to Principal Component Analysis
from sklearn.decomposition import PCA

# 5 different variance
variances = ["100%", "99%", "95%", "90%", "85%"]
pca = [PCA(), PCA(.99), PCA(.95), PCA(.90), PCA(.85)]
# results of each PCA variance
pca_fit = []

for p in pca:
    pca_content = {"fit": None, "transforms": {"train": None, "test": None}}
    pca_content["fit"] = p.fit(train_features)
    pca_content["transforms"]["train"] = p.transform(train_features)
    pca_content["transforms"]["test"] = p.transform(test_features)
    pca_fit.append(pca_content)

In [7]:
# checking the number of Principal Component
print("From 14 features")
for i in range(len(variances)):
    print(f"Principal Components with {variances[i]} variance:", pca_fit[i]["fit"].n_components_)

From 14 features
Principal Components with 100% variance: 80
Principal Components with 99% variance: 54
Principal Components with 95% variance: 36
Principal Components with 90% variance: 27
Principal Components with 85% variance: 21


# Applying Linear Discriminant Analysis

### Libraries Needed

In [8]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import StratifiedKFold
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score

import numpy as np

lda = LinearDiscriminantAnalysis()

### With Principal Component Analysis

In [9]:
# Evaluating of Model
for i in range(len(pca_fit)):
    # define model evaluation method
    cv = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)
    # evaluate model
    scores = cross_val_score(lda, pca_fit[i]["transforms"]["train"], np.ravel(train_lbl), scoring='accuracy', cv=cv)
    # summarize result
    print('Variance of %s:\nMean Accuracy: %.4f (%.4f)\n' % (variances[i], np.mean(scores), np.std(scores)))

Variance of 100%:
Mean Accuracy: 0.6937 (0.1062)

Variance of 99%:
Mean Accuracy: 0.7250 (0.0800)

Variance of 95%:
Mean Accuracy: 0.7875 (0.1016)

Variance of 90%:
Mean Accuracy: 0.7937 (0.0793)

Variance of 85%:
Mean Accuracy: 0.7875 (0.0750)



In [10]:
#Train the model
results = [] # where all the results will place

for i in range(len(pca_fit)):
    lda.fit(pca_fit[i]["transforms"]["train"], np.ravel(train_lbl))
    predictions = lda.predict(pca_fit[i]["transforms"]["test"])
    results.append(predictions)

In [11]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

for i in range(len(pca_fit)):
    print("Variance of", variances[i])
    print("Accuracy Score -", accuracy_score(test_lbl, results[i]))
    
    print("Confusion Matrix")
    print(confusion_matrix(test_lbl, results[i]))
    
    print("Classification Report")
    print(classification_report(test_lbl, results[i]))
    
    print()

Variance of 100%
Accuracy Score - 0.8
Confusion Matrix
[[21  1]
 [ 7 11]]
Classification Report
              precision    recall  f1-score   support

  No Finding       0.75      0.95      0.84        22
   Pneumonia       0.92      0.61      0.73        18

    accuracy                           0.80        40
   macro avg       0.83      0.78      0.79        40
weighted avg       0.82      0.80      0.79        40


Variance of 99%
Accuracy Score - 0.925
Confusion Matrix
[[22  0]
 [ 3 15]]
Classification Report
              precision    recall  f1-score   support

  No Finding       0.88      1.00      0.94        22
   Pneumonia       1.00      0.83      0.91        18

    accuracy                           0.93        40
   macro avg       0.94      0.92      0.92        40
weighted avg       0.93      0.93      0.92        40


Variance of 95%
Accuracy Score - 0.9
Confusion Matrix
[[22  0]
 [ 4 14]]
Classification Report
              precision    recall  f1-score   support

 

### Without Principal Component Analysis

In [12]:
# Performing towards the untransformed dataset

# define model evaluation method
cv = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)

# evaluate model
scores = cross_val_score(lda, train_features, np.ravel(train_lbl), scoring='accuracy', cv=cv)

# summarize result
print('Linear Discriminant Analysis Cross Validation Score:\nMean Accuracy - %.4f (%.4f)\n' % (np.mean(scores), np.std(scores)))

Linear Discriminant Analysis Cross Validation Score:
Mean Accuracy - 0.6937 (0.1062)



In [13]:
lda.fit(train_features, np.ravel(train_lbl))
predictions = lda.predict(test_features)

In [14]:
print("Linear Disriminant Analysis Performance")
print("Accuracy Score -", accuracy_score(test_lbl, predictions))

print("Confusion Matrix")
print(confusion_matrix(test_lbl, predictions))

print("Classification Report")
print(classification_report(test_lbl, predictions))

Linear Disriminant Analysis Performance
Accuracy Score - 0.8
Confusion Matrix
[[21  1]
 [ 7 11]]
Classification Report
              precision    recall  f1-score   support

  No Finding       0.75      0.95      0.84        22
   Pneumonia       0.92      0.61      0.73        18

    accuracy                           0.80        40
   macro avg       0.83      0.78      0.79        40
weighted avg       0.82      0.80      0.79        40

