# Retrieving the Dataset

In [1]:
# claiming the dataset
import pandas as pd

cxr_dataset = pd.read_csv("../features.csv")
cxr_dataset.head()

Unnamed: 0      mean0    variance0  skewness0  uniformity0      snr0  \
0           0  70.153934  1897.820090   0.155578          154  1.610366   
1           1  67.943420  1640.924326   0.179606          158  1.677271   
2           2  85.324244  1666.530997  -0.291033          153  2.090094   
3           3  84.536424  1134.304302  -0.575772          129  2.510031   
4           4  97.321200  1344.070831  -0.521123          164  2.654583   

        mean1    variance1  skewness1  uniformity1  ...  variance14  \
0   67.820031  1431.488738   0.101886          149  ...         0.0   
1   62.438356  1516.524282   0.382945          153  ...         0.0   
2   61.805752  1425.903805   0.326995          145  ...         0.0   
3   85.243692   957.789884  -0.289562          136  ...         0.0   
4  102.034224  1417.579232  -0.313052          155  ...         0.0   

   skewness14  uniformity14  snr14      mean15  variance15  skewness15  \
0         0.0             0    0.0    0.000000    0.000000    0.000000   
1         0.0             0    0.0  125.818182   59.954257    0.105233   
2         0.0             0    0.0    0.000000    0.000000    0.000000   
3         0.0             0    0.0  105.758879  247.749337   -0.316222   
4         0.0             0    0.0  121.310059  518.784337   -0.373516   

   uniformity15      snr15     label  
0             0   0.000000  COVID-19  
1            38  16.249253  COVID-19  
2             0   0.000000  COVID-19  
3            64   6.719092  COVID-19  
4            95   5.326027  COVID-19  

[5 rows x 82 columns]

In [2]:
drop_rows = cxr_dataset.loc[cxr_dataset['label'] == 'No Finding']
cxr_dataset.drop(drop_rows.index, inplace=True)
cxr_dataset['label'].unique()

array(['COVID-19', 'Pneumonia'], dtype=object)

# Splitting the dataset to train and test

In [3]:
# Getting the features needed

#get the feature columns
col_features = list(cxr_dataset.columns)
#get the label column
label = list(cxr_dataset.columns).pop()
#deleting label column from col
del col_features[0]
del col_features[len(col_features) - 1]

features = cxr_dataset.loc[:, col_features].values
labels = cxr_dataset.loc[:, label].values

display(pd.DataFrame(features))

0            1         2      3         4           5   \
0    70.153934  1897.820090  0.155578  154.0  1.610366   67.820031   
1    67.943420  1640.924326  0.179606  158.0  1.677271   62.438356   
2    85.324244  1666.530997 -0.291033  153.0  2.090094   61.805752   
3    84.536424  1134.304302 -0.575772  129.0  2.510031   85.243692   
4    97.321200  1344.070831 -0.521123  164.0  2.654583  102.034224   
..         ...          ...       ...    ...       ...         ...   
195  51.064488   991.876323  0.621574  126.0  1.621400   52.246799   
196  77.161636  1411.740183 -0.000914  146.0  2.053639   87.498747   
197  66.613725  1141.174321  0.262282  139.0  1.971913   69.993325   
198  88.374892  2123.046469 -0.183495  172.0  1.918002   69.177031   
199  77.365600  1558.363137  0.249453  148.0  1.959808   87.140704   

              6         7      8         9   ...   70   71   72   73   74  \
0    1431.488738  0.101886  149.0  1.792520  ...  0.0  0.0  0.0  0.0  0.0   
1    1516.524282  0.382945  153.0  1.603344  ...  0.0  0.0  0.0  0.0  0.0   
2    1425.903805  0.326995  145.0  1.636755  ...  0.0  0.0  0.0  0.0  0.0   
3     957.789884 -0.289562  136.0  2.754401  ...  0.0  0.0  0.0  0.0  0.0   
4    1417.579232 -0.313052  155.0  2.710018  ...  0.0  0.0  0.0  0.0  0.0   
..           ...       ...    ...       ...  ...  ...  ...  ...  ...  ...   
195   729.717895  0.936405  126.0  1.934115  ...  0.0  0.0  0.0  0.0  0.0   
196  1487.581661 -0.322070  152.0  2.268618  ...  0.0  0.0  0.0  0.0  0.0   
197  1126.649834  0.166404  150.0  2.085269  ...  0.0  0.0  0.0  0.0  0.0   
198  1328.168100  0.021836  148.0  1.898171  ...  0.0  0.0  0.0  0.0  0.0   
199   895.150339  0.015729  112.0  2.912548  ...  0.0  0.0  0.0  0.0  0.0   

             75          76        77    78         79  
0      0.000000    0.000000  0.000000   0.0   0.000000  
1    125.818182   59.954257  0.105233  38.0  16.249253  
2      0.000000    0.000000  0.000000   0.0   0.000000  
3    105.758879  247.749337 -0.316222  64.0   6.719092  
4    121.310059  518.784337 -0.373516  95.0   5.326027  
..          ...         ...       ...   ...        ...  
195    0.000000    0.000000  0.000000   0.0   0.000000  
196  109.789790  496.532388 -0.281837  90.0   4.927064  
197   98.164975  526.625068 -0.138085  89.0   4.277655  
198    0.000000    0.000000  0.000000   0.0   0.000000  
199  112.694414  241.149772  0.126530  55.0   7.257031  

[200 rows x 80 columns]

In [4]:
from sklearn.model_selection import train_test_split

# Separating test and train dataset
train_features, test_features, train_lbl, test_lbl = train_test_split( features, labels, test_size=0.2, random_state=0)

In [5]:
#Standardizing the Dataset
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fitting of training dataset only
scaler.fit(train_features)

# Apply transform to both the training set and the test set.
train_features = scaler.transform(train_features)
test_features = scaler.transform(test_features)

# Applying Principal Component Analysis

In [6]:
# Feeding it to Principal Component Analysis
from sklearn.decomposition import PCA

# 5 different variance
variances = ["100%", "99%", "95%", "90%", "85%"]
pca = [PCA(), PCA(.99), PCA(.95), PCA(.90), PCA(.85)]
# results of each PCA variance
pca_fit = []

for p in pca:
    pca_content = {"fit": None, "transforms": {"train": None, "test": None}}
    pca_content["fit"] = p.fit(train_features)
    pca_content["transforms"]["train"] = p.transform(train_features)
    pca_content["transforms"]["test"] = p.transform(test_features)
    pca_fit.append(pca_content)

In [7]:
# checking the number of Principal Component
print("From 14 features")
for i in range(len(variances)):
    print(f"Principal Components with {variances[i]} variance:", pca_fit[i]["fit"].n_components_)

From 14 features
Principal Components with 100% variance: 80
Principal Components with 99% variance: 56
Principal Components with 95% variance: 38
Principal Components with 90% variance: 28
Principal Components with 85% variance: 23


# Applying Linear Discriminant Analysis

### Libraries Needed

In [8]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import StratifiedKFold
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score

import numpy as np

lda = LinearDiscriminantAnalysis()

### With Principal Component Analysis

In [9]:
# Evaluating of Model
for i in range(len(pca_fit)):
    # define model evaluation method
    cv = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)
    # evaluate model
    scores = cross_val_score(lda, pca_fit[i]["transforms"]["train"], np.ravel(train_lbl), scoring='accuracy', cv=cv)
    # summarize result
    print('Variance of %s:\nMean Accuracy: %.4f (%.4f)\n' % (variances[i], np.mean(scores), np.std(scores)))

Variance of 100%:
Mean Accuracy: 0.6000 (0.0800)

Variance of 99%:
Mean Accuracy: 0.5687 (0.0859)

Variance of 95%:
Mean Accuracy: 0.5437 (0.1342)

Variance of 90%:
Mean Accuracy: 0.5687 (0.1517)

Variance of 85%:
Mean Accuracy: 0.5750 (0.1672)



In [10]:
#Train the model
results = [] # where all the results will place

for i in range(len(pca_fit)):
    lda.fit(pca_fit[i]["transforms"]["train"], np.ravel(train_lbl))
    predictions = lda.predict(pca_fit[i]["transforms"]["test"])
    results.append(predictions)

In [11]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

for i in range(len(pca_fit)):
    print("Variance of", variances[i])
    print("Accuracy Score -", accuracy_score(test_lbl, results[i]))
    
    print("Confusion Matrix")
    print(confusion_matrix(test_lbl, results[i]))
    
    print("Classification Report")
    print(classification_report(test_lbl, results[i]))
    
    print()

Variance of 100%
Accuracy Score - 0.55
Confusion Matrix
[[14  4]
 [14  8]]
Classification Report
              precision    recall  f1-score   support

    COVID-19       0.50      0.78      0.61        18
   Pneumonia       0.67      0.36      0.47        22

    accuracy                           0.55        40
   macro avg       0.58      0.57      0.54        40
weighted avg       0.59      0.55      0.53        40


Variance of 99%
Accuracy Score - 0.65
Confusion Matrix
[[14  4]
 [10 12]]
Classification Report
              precision    recall  f1-score   support

    COVID-19       0.58      0.78      0.67        18
   Pneumonia       0.75      0.55      0.63        22

    accuracy                           0.65        40
   macro avg       0.67      0.66      0.65        40
weighted avg       0.68      0.65      0.65        40


Variance of 95%
Accuracy Score - 0.6
Confusion Matrix
[[14  4]
 [12 10]]
Classification Report
              precision    recall  f1-score   support

 

### Without Principal Component Analysis

In [12]:
# Performing towards the untransformed dataset

# define model evaluation method
cv = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)

# evaluate model
scores = cross_val_score(lda, train_features, np.ravel(train_lbl), scoring='accuracy', cv=cv)

# summarize result
print('Linear Discriminant Analysis Cross Validation Score:\nMean Accuracy - %.4f (%.4f)\n' % (np.mean(scores), np.std(scores)))

Linear Discriminant Analysis Cross Validation Score:
Mean Accuracy - 0.6000 (0.0800)



In [13]:
lda.fit(train_features, np.ravel(train_lbl))
predictions = lda.predict(test_features)

In [14]:
print("Linear Disriminant Analysis Performance")
print("Accuracy Score -", accuracy_score(test_lbl, predictions))

print("Confusion Matrix")
print(confusion_matrix(test_lbl, predictions))

print("Classification Report")
print(classification_report(test_lbl, predictions))

Linear Disriminant Analysis Performance
Accuracy Score - 0.55
Confusion Matrix
[[14  4]
 [14  8]]
Classification Report
              precision    recall  f1-score   support

    COVID-19       0.50      0.78      0.61        18
   Pneumonia       0.67      0.36      0.47        22

    accuracy                           0.55        40
   macro avg       0.58      0.57      0.54        40
weighted avg       0.59      0.55      0.53        40

